### ISSUE TITLE
/grant not working

### ISSUE THREAD

**Issue by DI3HARD139** [MinetestForFun/mysql_auth#6]
When using /grant <player> <priv> it returns "Player does not exist". No error is given.

**Comment by ElementW** [comment]
Thanks for reporting. Once again, the following, in `builtin/game/chatcommands.lua`, proves MT's inconsistency:
```lua
elseif not core.auth_table[grantname] then
	return false, "Player " .. grantname .. " does not exist."
end
```
Where, as you can see, they directly use `core.auth_table`, which is supposed to never be accessed like that since they provide an API to change the auth mechanism.

Stay tuned, I'm going to yell at them devs with a(nother) PR.

**Comment by ElementW** [comment]
minetest/minetest#4974

Since MFF severs aren't following upstream MT commits (and since even for a trivial fix it might take months to get merged), manual fixing will be required.

**Comment by BetterToAutomateTheWorld** [comment]
Thank you for this report @DI3HARD139 

Thank you for the quick fix @ElementW 
Let's wait months or years for this merge upstream in Minetest Core...

I will apply manually this tweak when we will update our servers from 0.4.14-stable to 0.4.15-stable

**Comment by DI3HARD139** [comment]
Speaking of said update, would anyone happen to know where I could find the "chatcommands.lua" file for a non-portable install?
OS: Ubuntu Server 16.04.1 x64

**Comment by ghost** [comment]
in /usr/share/minetest/builtin/game/chatcommands.lua
or 
/usr/share/minetestserver/builtin/game/chatcommands.lua

or to search install "mlocate"

`sudo updatedb`

`mlocate game/chatcommands.lua`

**Comment by DI3HARD139** [comment]
Perfect! Thanks so much! IDK why I kept searching in the "minetest" folder in the ./minetest directory :P
EDIT: Back to searching as for some reason it didn't compile to that directory...
EDIT: Found it. Mine was in /usr/local/share/minetest
